# Generated by Django 5.1.5 on 2025-01-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0010_alter_address_mobile_number_alter_address_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mobile_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
