# Generated by Django 5.1.5 on 2025-01-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0011_alter_address_mobile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
