# Generated by Django 5.1.5 on 2025-01-30 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0013_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='Booking_date',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='booktable',
            old_name='Email',
            new_name='user_email',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='booktable',
            name='Phone_number',
        ),
        migrations.AddField(
            model_name='booktable',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='booktable',
            name='phone_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
    ]
