# Generated by Django 5.1.5 on 2025-01-30 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0014_rename_booking_date_booktable_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='booking_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='user_name',
            field=models.CharField(max_length=255),
        ),
    ]
