# Generated by Django 5.1.5 on 2025-02-06 08:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0015_alter_booktable_booking_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
