# Generated by Django 5.1.5 on 2025-02-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0017_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(),
        ),
    ]
